services:
  - type: web
    name: laravel-api-railway
    env: docker
    plan: free
    branch: main
    dockerfilePath: Dockerfile
    envVars:
      - fromFile: .env.production
    preDeployCommand: |
      php artisan migrate --force
